spring.application.name=job-aggregator
spring.datasource.url=jdbc:postgresql://localhost:5434/nvd
spring.datasource.username=nvd
spring.datasource.password=nvd123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html
