const layout = {
  page: {
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
}

const header = {
  header: {
    borderBottom: '1px solid var(--border)',
    backdropFilter: 'blur(12px)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
    padding: '0 clamp(1rem, 4vw, 3rem)',
  },
  headerInner: {
    maxWidth: 1200,
    margin: '0 auto',
    height: 64,
    gap: '1rem',
  },
  headerRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
  },
  logo: {
    fontFamily: 'var(--font-ui)',
    fontWeight: 800,
    fontSize: '1.35rem',
    color: 'var(--text)',
  },
  logoAccent: {
    color: 'var(--accent)',
  },
  headerBadge: {
    fontFamily: 'var(--font-mono)',
    fontSize: '0.72rem',
    color: 'var(--muted)',
    background: 'var(--border)',
    padding: '3px 12px',
    borderRadius: 99,
  },
  themeBtn: {
    width: 38,
    height: 38,
    borderRadius: 99,
    border: '1px solid var(--border)',
    background: 'var(--surface)',
    color: 'var(--text)',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s',
    flexShrink: 0,
  },
}

const hero = {
  hero: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: 'clamp(2.5rem,6vh,5rem) clamp(1rem,4vw,3rem) 0',
  },
  heroTitle: {
    fontFamily: 'var(--font-ui)',
    fontWeight: 800,
    fontSize: 'clamp(2.25rem,5vw,3.75rem)',
    lineHeight: 1.08,
    maxWidth: 680,
  },
  heroSub: {
    marginTop: '0.75rem',
    color: 'var(--muted)',
    fontWeight: 400,
    maxWidth: 520,
  },
}

const filters = {
  filterPanel: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: 'clamp(1.5rem,3vw,2rem) clamp(1rem,4vw,3rem)',
  },
  filterCard: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 16,
    padding: '1.5rem',
    boxShadow: 'var(--shadow)',
  },
  filterGrid: {
    gap: '1rem',
    marginBottom: '1rem',
  },
  filterGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.35rem',
  },
  filterGroupWide: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.35rem',
  },
  label: {
    fontFamily: 'var(--font-mono)',
    fontSize: '0.66rem',
    fontWeight: 600,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--muted)',
  },
  input: {
    background: 'var(--bg)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    color: 'var(--text)',
    fontFamily: 'var(--font-ui)',
    fontSize: '0.92rem',
    fontWeight: 500,
    padding: '0.6rem 0.9rem',
    outline: 'none',
    transition: 'border-color 0.15s',
    width: '100%',
    appearance: 'none',
    WebkitAppearance: 'none',
  },
  dateRow: {
    gap: '0.5rem',
    alignItems: 'center',
  },
  dateSep: {
    color: 'var(--muted)',
    fontSize: '0.85rem',
    whiteSpace: 'nowrap',
  },
  filterBottom: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: '0.75rem',
  },
  sourceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    flexWrap: 'wrap',
  },
  sourceLabel: {
    fontFamily: 'var(--font-mono)',
    fontSize: '0.66rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--muted)',
  },
  pill: {
    fontSize: '0.78rem',
    fontWeight: 600,
    padding: '4px 14px',
    borderRadius: 99,
    border: '1px solid var(--border)',
    cursor: 'pointer',
    background: 'transparent',
    color: 'var(--muted)',
    fontFamily: 'var(--font-ui)',
    transition: 'all 0.15s',
  },
  pillActive: {
    background: 'rgba(200,55,45,0.12)',
    borderColor: 'var(--accent)',
    color: 'var(--accent)',
    fontWeight: 500,
  },
  searchBtn: {
    background: 'var(--accent)',
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    fontFamily: 'var(--font-ui)',
    fontSize: '0.9rem',
    fontWeight: 700,
    padding: '0.65rem 1.8rem',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    transition: 'opacity 0.15s',
  },
  resetBtn: {
    background: 'transparent',
    color: 'var(--muted)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    fontFamily: 'var(--font-ui)',
    fontSize: '0.9rem',
    fontWeight: 600,
    padding: '0.65rem 1.2rem',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
}

const results = {
  results: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: '0 clamp(1rem,4vw,3rem) 4rem',
  },
  resultsTop: {
    gap: '1rem',
    marginBottom: '1.25rem',
  },
  resultsMeta: {
    fontSize: '0.8rem',
    color: 'var(--muted)',
    fontFamily: 'var(--font-mono)',
  },
  pagination: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  },
  pageBtn: {
    background: 'var(--surface)',
    color: 'var(--text)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    fontFamily: 'var(--font-ui)',
    fontSize: '0.84rem',
    fontWeight: 700,
    padding: '0.5rem 0.85rem',
    cursor: 'pointer',
    transition: 'all 0.15s',
  },
  pageBtnDisabled: {
    opacity: 0.45,
    cursor: 'not-allowed',
  },
  pageText: {
    fontFamily: 'var(--font-mono)',
    fontSize: '0.78rem',
    color: 'var(--muted)',
    minWidth: 64,
    textAlign: 'center',
  },
  grid: {
    gridAutoRows: '1fr',
    alignItems: 'stretch',
    gap: '1rem',
  },
}

const card = {
  cardWrap: {
    height: '100%',
  },
  card: {
    height: '100%',
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 12,
    padding: '1.4rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.6rem',
    boxShadow: 'var(--shadow)',
    transition: 'transform 0.15s, box-shadow 0.15s',
  },
  cardSource: {
    fontFamily: 'var(--font-mono)',
    fontSize: '0.66rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: 'var(--accent)',
    fontWeight: 600,
  },
  cardTitle: {
    fontFamily: 'var(--font-ui)',
    fontWeight: 700,
    fontSize: '1.05rem',
    lineHeight: 1.35,
    color: 'var(--text)',
  },
  cardCompany: {
    fontSize: '0.86rem',
    fontWeight: 500,
    color: 'var(--muted)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
  },
  cardDesc: {
    fontSize: '0.86rem',
    lineHeight: 1.6,
    display: '-webkit-box',
    WebkitLineClamp: 3,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  cardMeta: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '0.4rem',
    marginTop: '0.25rem',
  },
  tag: {
    fontSize: '0.74rem',
    fontWeight: 600,
    padding: '3px 10px',
    borderRadius: 99,
    border: '1px solid var(--border)',
    color: 'var(--muted)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.3rem',
    background: 'var(--bg)',
  },
  tagDeadline: {
    color: '#C87010',
    borderColor: 'rgba(200,130,0,0.35)',
    background: 'rgba(200,130,0,0.08)',
  },
  cardFooter: {
    marginTop: 'auto',
    paddingTop: '0.75rem',
    borderTop: '1px solid var(--border)',
  },
  applyBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.4rem',
    background: 'var(--text)',
    color: 'var(--bg)',
    padding: '0.55rem 1.1rem',
    borderRadius: 8,
    fontSize: '0.82rem',
    fontWeight: 700,
    textDecoration: 'none',
    transition: 'opacity 0.15s',
  },
}

const state = {
  stateBox: {
    textAlign: 'center',
    padding: '5rem 2rem',
    color: 'var(--muted)',
  },
  stateBig: {
    fontSize: '3rem',
    marginBottom: '0.75rem',
  },
  stateText: {
    fontSize: '1rem',
    fontWeight: 500,
  },
}

export const S = {
  ...layout,
  ...header,
  ...hero,
  ...filters,
  ...results,
  ...card,
  ...state,
}
